---
- name: "Download Wordpress Package"
  get_url:
    url: 'https://wordpress.org/wordpress-5.0.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: "Unpacking Wordpress Package"
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: "Creating Wordpress Config file"
  copy:
    src: "{{ wp_workdir }}/wp-config-sample.php"
    dest: "{{ wp_workdir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Configuring Wordpress config file"
  replace:
    path: "{{ wp_workdir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_db_user }}" }
    - { regex: 'password_here', value: "{{ wp_db_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_host }}" }
  become: yes

- name: "Configuring Apache "
  replace:
    path: '/etc/apache2/sites-available/000-default.conf'
    regexp: '/var/www/html'
    replace: "{{ wp_workdir }}"
  become: yes
  notify:
    - restart apache